name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build and Push Crocodile Docker image
      run: |
        image_tag="${{ vars.IMAGE_NAME }}:$(date +%s)"
        docker build . --file ./images/crocodile/Dockerfile --tag "$image_tag"
        echo -n "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USER }}" --password-stdin
        docker push ${image_tag}
