name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  GHCR_USER: JBerny

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Push Docker image
      run: |
        
        image_tag="${{ env.IMAGE_NAME }}:$(date +%s)"
        docker build . --file Dockerfile --tag "$image_tag"
        echo -n "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${GHCR_USER} --password-stdin
        docker push ${image_tag}
